# Generated by Django 4.2.13 on 2024-06-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='prenom',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Adress_user',
            field=models.CharField(default='', max_length=10, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Phone_user',
            field=models.CharField(default='', max_length=10, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default='', max_length=30, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default='', max_length=30, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Utilisateur actif'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Membre du personnel'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superutilisateur'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=None, verbose_name='Dernière connexion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
