# Generated by Django 4.2.13 on 2024-06-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_remove_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('moderateur', 'Modérateur'), ('membre', 'Membre'), ('client', 'Client'), ('visiteur', 'Visiteur')], default='visiteur', max_length=20),
        ),
    ]
