# Generated by Django 4.2.13 on 2024-06-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_customuser_type_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Adress_user',
            new_name='adress_user',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Phone_user',
            new_name='phone_user',
        ),
    ]
