# Generated by Django 4.2.13 on 2024-06-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adress_user',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_user',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Telephone'),
        ),
    ]
