# Generated by Django 4.2.13 on 2024-06-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_alter_customuser_adress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'inscription"),
        ),
    ]
