# Generated by Django 4.2.13 on 2024-07-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0013_customuser_photo_couverture_customuser_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio_user',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ville_user',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Ville'),
        ),
    ]
