# Generated by Django 4.2.13 on 2024-07-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0015_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
    ]
