# Generated by Django 4.2.13 on 2024-07-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0016_customuser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_couverture',
            field=models.ImageField(default='uploads/photo_couverture/couv2.jpg', null=True, upload_to='uploads/profile/photo_couverture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo_profil',
            field=models.ImageField(default='uploads/photo_profil/photo_profil_default.jpg', null=True, upload_to='uploads/profile/photo_profil'),
        ),
    ]
