# Generated by Django 4.2.13 on 2024-07-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0017_alter_customuser_photo_couverture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_user',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Country'),
        ),
    ]
