# Generated by Django 4.2.13 on 2024-07-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0018_customuser_country_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthdate',
        ),
    ]
