# Generated by Django 4.2.13 on 2024-07-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0019_remove_customuser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('moderateur', 'Modérateur'), ('membre', 'Membre'), ('client', 'Client'), ('visiteur', 'Visiteur')], default='client', max_length=20),
        ),
    ]
