# Generated by Django 4.2.13 on 2024-07-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postimage',
            field=models.ImageField(null=True, upload_to='uploads/posts_image/'),
        ),
    ]
