# Generated by Django 4.2.13 on 2024-07-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/posts_image/'),
        ),
    ]
