# Generated by Django 4.2.13 on 2024-07-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_reservationseance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationseance',
            name='statut',
            field=models.CharField(choices=[('attente', 'en attente'), ('accepté', 'acceptee'), ('refusee', 'refusee'), ('terminee', 'terminee')], default='en attente', max_length=20),
        ),
    ]
